# For more information: https://laravel.com/docs/sail
version: '3'
services:
    locus.test:
        build:
            context: ./
            dockerfile: ./docker/.Dockerfile
        ports:
            - '${APP_PORT:-80}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            MYSQL_HOST: '${DB_HOST}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '.:/app'
        networks:
            - locus
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'locus-mariadb:/var/lib/mysql'
            - './docker/create-database.sh:/docker-entrypoint-initdb.d/10-create-database.sh'

        networks:
            - locus
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    locus:
        driver: bridge
volumes:
    locus-mariadb:
        driver: local