version: '3'
services:
    locus.frontend:
        build:
            context: ./frontend
            dockerfile: ./docker/.Dockerfile
        ports:
            - '${FRONTEND_APP_PORT:-80}:4200'
        environment:
            API_HOST: '${API_HOST}'
            FRONT_HOST: '${FRONT_HOST}'
        volumes:
            - 'frontend-node-modules:/app/node_modules'
            - './frontend:/app'
        networks:
            - locus
        depends_on:
            - locus.backend
        command: sh -c "npm run ng serve --host=0.0.0.0 --watch"


    locus.backend:
        build:
            context: ./backend
            dockerfile: ./docker/.Dockerfile
        ports:
            - '${BACKEND_APP_PORT:-88}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            MYSQL_HOST: '${DB_HOST}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            FRONT_HOST: '${FRONT_HOST}'
        volumes:
            - './backend:/app'
        networks:
            - locus
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'locus-mariadb:/var/lib/mysql'
            - './backend/docker/create-database.sh:/docker-entrypoint-initdb.d/10-create-database.sh'

        networks:
            - locus
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    locus:
        driver: bridge
volumes:
    locus-mariadb:
        driver: local

    frontend-node-modules:
        driver: local